import { uuidv7 } from "uuidv7";
import type { Prisma } from "../../src/generated/prisma/client.ts";
import { type Injectable, injected } from "../../src/prisma/injected.ts";
import { type ActorContext, withTenant } from "../../src/prisma/with-tenant.ts";
import type { ClinicBlueprint } from "./blueprint.ts";
import { latinSearchKey } from "../../src/modules/patients/domain/transliterate.ts";
import { DIAGNOSES, DOCTOR_NOTES, TREATMENT_PLANS } from "./arabic-names.ts";
import { generateAppointments, generatePatients } from "./generate.ts";
import { Prng } from "./prng.ts";
import type { SeededStaff } from "./seed-staff.ts";

/**
 * Volume data: patients, and three months of appointments with the visits and payments that
 * follow from them.
 *
 * Everything here is written inside withTenant() with the system actor, in chunks. The chunking is
 * not cosmetic -- see CHUNK_SIZE below.
 */

/**
 * Rows per transaction.
 *
 * withTenant() wraps its callback in `prisma.$transaction()`, whose default timeout is five
 * seconds. Seeding a clinic in one call comfortably exceeds that: each insert also fires the audit
 * trigger, so the real write volume is roughly double the row count. Rather than widen the
 * timeout -- which would mean changing withTenant()'s signature for the benefit of a dev script,
 * and weakening a limit that exists to stop production transactions holding locks -- the seed
 * fits itself to the guarantee and commits in batches.
 *
 * The trade-off is honest and worth stating: a failure midway leaves a partially seeded clinic
 * rather than nothing. That is acceptable precisely because seeding is not reversible anyway (see
 * index.ts), and the recovery for both cases is identical: reset the database and re-run.
 */
const CHUNK_SIZE = 150;


async function inChunks<T>(
  items: readonly T[],
  tenantId: string,
  actor: ActorContext,
  write: (tx: Parameters<Parameters<typeof withTenant>[2]>[0], batch: T[]) => Promise<void>,
): Promise<void> {
  for (let start = 0; start < items.length; start += CHUNK_SIZE) {
    const batch = items.slice(start, start + CHUNK_SIZE);
    await withTenant(tenantId, actor, async (tx) => {
      await write(tx, batch);
    });
  }
}


export interface ClinicalTotals {
  patients: number;
  appointments: number;
  visits: number;
  payments: number;
}

export async function seedClinical(
  clinic: ClinicBlueprint,
  staff: SeededStaff,
  actor: ActorContext,
  referenceDate: Date,
  phoneBase: number,
): Promise<ClinicalTotals> {
  const rng = new Prng(clinic.randomSeed);
  const { tenantId, receptionUserId } = staff;
  // The person who authorises a discount above the ceiling (ruling 4). The owner, falling back to
  // reception only so the seed cannot fail on a clinic blueprint with no owner key.
  const ownerUserId = staff.userIdByKey.get("owner") ?? receptionUserId;

  const patients = generatePatients(clinic, rng, phoneBase);

  // One contact per household, not per patient: a quarter of these patients share somebody else's
  // number, and inserting the contact once per member would fail on the primary key.
  const contacts = [...new Map(patients.map((patient) => [patient.contactId, patient])).values()];

  await inChunks(contacts, tenantId, actor, async (tx, batch) => {
    await tx.contact.createMany({
      data: batch.map((patient) =>
        injected({
          id: patient.contactId,
          phoneE164: patient.phoneE164,
          whatsappOptIn: true,
        }),
      ),
    });
  });

  await inChunks(patients, tenantId, actor, async (tx, batch) => {
    await tx.patient.createMany({
      data: batch.map((patient) =>
        injected({
          id: patient.id,
          contactId: patient.contactId,
          // name_search_ar is generated by Postgres from full_name_ar; name_search_latin is
          // application-maintained, which is the volatility split D19 describes. Written here the
          // same way a real create will write it, so the seed exercises the real path.
          fullNameAr: patient.fullName,
          fullNameEn: patient.fullNameEn,
          nameSearchLatin: latinSearchKey(patient.fullName, patient.fullNameEn),
          phoneE164: patient.phoneE164,
          gender: patient.gender,
          address: patient.address,
          relationshipToContact: patient.relationshipToContact,
          status: "ACTIVE",
        }),
      ),
    });
  });

  // Phase 5 PR 1: the clinic's insurance registry, and cover for a few patients. Without these a
  // review build shows an empty registry, reception has nothing to pick from, and the payer split
  // has no insurer to name -- three screens that look unfinished because the data is.
  const insurerIds = clinic.insurers.map(() => uuidv7());
  await inChunks(clinic.insurers, tenantId, actor, async (tx, batch) => {
    await tx.insuranceCompany.createMany({
      data: batch.map((insurer, index) =>
        injected({
          id: insurerIds[index] as string,
          name: insurer.name,
          type: insurer.type,
          contractNumber: insurer.contractNumber,
          // A contract that started last year and runs to the end of next: current on any day a
          // review build is opened, without reading the clock (SEED_REFERENCE_DATE is the instant).
          contractStart: new Date(Date.UTC(referenceDate.getUTCFullYear() - 1, 0, 1)),
          contractEnd: new Date(Date.UTC(referenceDate.getUTCFullYear() + 1, 11, 31)),
          contactPerson: insurer.contactPerson,
          phone: insurer.phone,
          email: insurer.email,
          claimSubmissionMethod: insurer.claimSubmissionMethod,
          paymentTermsDays: insurer.paymentTermsDays,
          priorApprovalRequired: insurer.priorApprovalRequired,
        }),
      ),
    });
  });

  // Every eighth patient carries cover, alternating between the two companies. Enough that a
  // reviewer opening the patient book meets one quickly, and far from everyone -- which is what an
  // Egyptian outpatient clinic looks like.
  const covered = patients.filter((_, index) => index % 8 === 0);
  const policies = covered.map((patient, index) => ({
    id: uuidv7(),
    coverageId: uuidv7(),
    patient,
    insurerIndex: index % clinic.insurers.length,
    // Numbered from the index, not from the uuid. `uuidv7` begins with a 48-bit timestamp, so the
    // first eight hex characters of two ids minted in the same millisecond are identical -- which
    // the (tenant, insurer_name, policy_number) unique index caught on the first fresh seed.
    number: `POL-${String(index + 1).padStart(5, "0")}`,
  }));

  await inChunks(policies, tenantId, actor, async (tx, batch) => {
    await tx.insurancePolicy.createMany({
      data: batch.map((policy) =>
        injected({
          id: policy.id,
          contactId: policy.patient.contactId,
          companyId: insurerIds[policy.insurerIndex] as string,
          insurerName: clinic.insurers[policy.insurerIndex]!.name,
          planName: policy.insurerIndex === 0 ? "Gold" : "Standard",
          policyNumber: policy.number,
          policyholderName: policy.patient.fullName,
          validFrom: new Date(Date.UTC(referenceDate.getUTCFullYear() - 1, 0, 1)),
          validTo: new Date(Date.UTC(referenceDate.getUTCFullYear() + 1, 11, 31)),
        }),
      ),
    });
  });

  await inChunks(policies, tenantId, actor, async (tx, batch) => {
    await tx.patientInsurance.createMany({
      data: batch.map((policy) =>
        injected({
          id: policy.coverageId,
          patientId: policy.patient.id,
          policyId: policy.id,
          relationshipToPolicyholder: "SELF",
          isPrimary: true,
        }),
      ),
    });
  });

  const appointments = generateAppointments(clinic, staff, rng, patients, referenceDate);

  // Every appointment booked through this system from now on carries the price reception quoted
  // (PHASE-4.md §5). The seed describes a clinic that books through this system, so leaving the
  // column NULL here would render "not recorded" across a review build on rows that, in the
  // fiction the seed is telling, were quoted at the desk like any other.
  //
  // Deterministic: the price comes from the blueprint via the service the generator already chose,
  // not from a second draw on the RNG and not from the clock.
  const quotedPriceByServiceId = new Map(
    staff.serviceIds.map((serviceId, index) => [serviceId, staff.servicePrices[index]!]),
  );

  await inChunks(appointments, tenantId, actor, async (tx, batch) => {
    await tx.appointment.createMany({
      data: batch.map((appointment) =>
        injected({
          id: appointment.id,
          patientId: appointment.patientId,
          doctorId: appointment.doctorId,
          serviceId: appointment.serviceId,
          quotedPriceMinor: quotedPriceByServiceId.get(appointment.serviceId) ?? null,
          scheduledStart: appointment.scheduledStart,
          scheduledEnd: appointment.scheduledEnd,
          status: appointment.status,
          source: appointment.source,
          complaintSummary: appointment.complaintSummary,
          bookingNotes: appointment.bookingNotes,
          cancellationReason: appointment.cancellationReason,
          createdBy: receptionUserId,
          updatedBy: receptionUserId,
          // Taken from the generator, not re-derived from the status here. Deriving them in this
          // file is what confined the queue timestamps to COMPLETED: a status this writer had no
          // rule for got three nulls, and `waitedMs` on the board is computed from `arrivedAt`.
          arrivedAt: appointment.arrivedAt,
          waitingStartedAt: appointment.waitingStartedAt,
          consultationStartedAt: appointment.consultationStartedAt,
          consultationEndedAt: appointment.consultationEndedAt,
        }),
      ),
    });
  });

  // One CREATED event per appointment, plus a STATUS_CHANGED for anything that moved off BOOKED.
  // appointment_events is append-only (D5), so these can never be edited or removed afterwards.
  const events = appointments.flatMap((appointment): Injectable<Prisma.AppointmentEventCreateManyInput>[] => {
    const created: Injectable<Prisma.AppointmentEventCreateManyInput> = {
      id: uuidv7(),
      appointmentId: appointment.id,
      eventType: "CREATED" as const,
      fromStatus: null,
      toStatus: "BOOKED" as const,
      actorUserId: receptionUserId,
      reason: null as string | null,
    };
    if (appointment.status === "BOOKED") return [created];
    return [
      created,
      {
        id: uuidv7(),
        appointmentId: appointment.id,
        eventType: "STATUS_CHANGED" as const,
        fromStatus: "BOOKED" as const,
        toStatus: appointment.status,
        actorUserId: receptionUserId,
        reason: appointment.cancellationReason,
      },
    ];
  });

  await inChunks(events, tenantId, actor, async (tx, batch) => {
    await tx.appointmentEvent.createMany({ data: batch.map((event) => injected(event)) });
  });

  const completed = appointments.filter((appointment) => appointment.status === "COMPLETED");

  const visits = completed.map((appointment) => {
    const doctorUserKey = staff.doctorKeys.find((key) => staff.doctorIdByKey.get(key) === appointment.doctorId);
    const createdBy = (doctorUserKey && staff.userIdByKey.get(doctorUserKey)) ?? receptionUserId;
    const followUpDays = rng.chance(0.45) ? rng.pick([7, 14, 30, 60]) : null;
    return {
      id: uuidv7(),
      appointment,
      // `id` is deliberately absent here and supplied at the write below, from the id generated
      // alongside this row -- payments reference it, so it has to exist before the visit is
      // written. Injectable<> makes it optional rather than requiring a placeholder value.
      row: {
        patientId: appointment.patientId,
        doctorId: appointment.doctorId,
        appointmentId: appointment.id,
        complaint: appointment.complaintSummary,
        examination: rng.pick(DOCTOR_NOTES),
        diagnosis: rng.pick(DIAGNOSES),
        treatmentPlan: rng.pick(TREATMENT_PLANS),
        doctorNotes: rng.chance(0.6) ? rng.pick(DOCTOR_NOTES) : null,
        followUpIntervalDays: followUpDays,
        followUpDate: followUpDays === null
          ? null
          : new Date(appointment.scheduledEnd.getTime() + followUpDays * 86_400_000),
        status: "COMPLETED" as const,
        completedAt: appointment.scheduledEnd,
        createdBy,
      } satisfies Injectable<Prisma.VisitCreateManyInput>,
    };
  });

  await inChunks(visits, tenantId, actor, async (tx, batch) => {
    await tx.visit.createMany({
      data: batch.map((visit) => injected({ ...visit.row, id: visit.id })),
    });
  });

  // Money is integer minor units throughout (CLAUDE.md).
  //
  // Phase 5 PR 5 split the invoice from the receipt: what the visit costs is a `visit_charges` row,
  // and what was handed over is a `payments` row that settles it. `receipt_number` and
  // `receipt_date` are deliberately absent -- a trigger allocates them, gaplessly, per clinic.
  const charges: Injectable<Prisma.VisitChargeCreateManyInput>[] = [];
  const payments: Injectable<Prisma.PaymentCreateManyInput>[] = [];

  for (const visit of visits) {
    const price = visit.appointment.servicePriceMinor;
    const discount = rng.chance(0.15) ? Math.round((price * rng.int(10, 30)) / 100 / 500) * 500 : 0;
    const amountDue = price - discount;
    const status = rng.weighted([["PAID", 75], ["PARTIAL", 15], ["UNPAID", 10]] as const);
    const amountPaid = status === "PAID" ? amountDue : status === "PARTIAL" ? Math.round(amountDue / 2 / 500) * 500 : 0;
    const method = rng.weighted([["CASH", 70], ["INSTAPAY", 15], ["CARD", 10], ["MOBILE_WALLET", 5]] as const);

    // Ruling 4: a discount above the clinic's ceiling needs somebody named as authorising it, and
    // the database refuses one without. The seed deliberately produces both kinds -- most within
    // the ceiling, some above it and authorised -- so a review build shows the real behaviour
    // rather than only the easy path. CI caught this: a fresh database rejected the seed outright.
    const ceiling = Math.min(Math.floor((price * 10) / 100), 5_000);
    const authorised = discount > ceiling;

    const chargeId = uuidv7();
    charges.push({
      id: chargeId,
      visitId: visit.id,
      patientId: visit.appointment.patientId,
      subtotalMinor: price,
      discountMinor: discount,
      discountReason: discount > 0 ? "خصم متابعة" : null,
      discountAuthorisedByUserId: authorised ? ownerUserId : null,
      status: amountPaid >= amountDue ? "SETTLED" : "OPEN",
    });

    // An UNPAID visit has a charge and no receipt: nothing was handed over, and a receipt for zero
    // would be a document saying money changed hands when it did not.
    if (amountPaid > 0) {
      payments.push({
        id: uuidv7(),
        patientId: visit.appointment.patientId,
        appointmentId: visit.appointment.id,
        visitId: visit.id,
        chargeId,
        amountMinor: amountPaid,
        method,
        status,
        collectedByUserId: receptionUserId,
        paidAt: visit.appointment.scheduledEnd,
        confirmationMethod: method === "CASH" ? ("CASH" as const) : null,
      });
    }
  }

  await inChunks(charges, tenantId, actor, async (tx, batch) => {
    await tx.visitCharge.createMany({ data: batch.map((charge) => injected(charge)) });
  });

  await inChunks(payments, tenantId, actor, async (tx, batch) => {
    await tx.payment.createMany({ data: batch.map((payment) => injected(payment)) });
  });

  return {
    patients: patients.length,
    appointments: appointments.length,
    visits: visits.length,
    payments: payments.length,
  };
}
