// Every fixed-template line the step machine (whatsapp-flow.ts) sends, in both languages, in one
// place -- so a wording change never means finding the third of five places a phrase was typed.
//
// Egyptian-register Arabic, not stiff MSA (Q9): "إزيك" over "كيف حالك", "معاك" over "معك". Nothing
// here is generated by the model -- see whatsapp-flow.ts's own header for why that split exists.

export type Lang = "ar" | "en";

/** Arabic script anywhere in the message outweighs everything else -- a patient who writes mostly
 *  in Arabic but types a doctor's English name is still writing Arabic. Falls back to the
 *  conversation's already-known language when the text carries no signal either way (a bare
 *  emoji, a lone number), and only to "ar" -- the clinic's default -- when there truly is none yet. */
export function detectLang(text: string, fallback: Lang = "ar"): Lang {
  if (/[\u0600-\u06FF]/.test(text)) return "ar";
  if (/[a-zA-Z]/.test(text)) return "en";
  return fallback;
}

function pick(lang: Lang, ar: string, en: string): string {
  return lang === "ar" ? ar : en;
}

export const T = {
  welcome: (lang: Lang, clinicName: string) =>
    pick(
      lang,
      `أهلاً بيك في ${clinicName} 👋`,
      `Welcome to ${clinicName} 👋`,
    ),

  intentQuestion: (lang: Lang) =>
    pick(lang, "تحب تعمل إيه النهاردة؟", "What would you like to do today?"),
  intentBooking: (lang: Lang) => pick(lang, "حجز ميعاد", "Book an appointment"),
  intentComplaint: (lang: Lang) => pick(lang, "الإبلاغ عن مشكلة", "Report an issue"),
  intentUnclear: (lang: Lang) =>
    pick(lang, "معلش، مفهمتش قصدك. اختار من دول:", "Sorry, I didn't quite catch that. Please choose:"),

  // -- identity ------------------------------------------------------------------------------
  identityConfirmSingle: (lang: Lang, name: string, phone: string) =>
    pick(lang, `لقيت الرقم ده مسجل باسم ${name} (${phone}). ده حضرتك؟`, `This number is registered as ${name} (${phone}). Is that you?`),
  identityConfirmMultiple: (lang: Lang) =>
    pick(lang, "لقيت أكتر من اسم مسجل على الرقم ده. مين اللي بيتكلم؟", "This number has more than one person registered. Who's this for?"),
  identityOptionSomeoneElse: (lang: Lang) =>
    pick(lang, "شخص تاني", "Someone else"),
  yes: (lang: Lang) => pick(lang, "أيوه", "Yes"),
  no: (lang: Lang) => pick(lang, "لأ", "No"),

  phoneChoiceQuestion: (lang: Lang) =>
    pick(lang, "هنستخدم رقم الواتساب ده ولا رقم تاني؟", "Should we use this WhatsApp number, or a different one?"),
  phoneChoiceThisNumber: (lang: Lang) => pick(lang, "هذا الرقم", "This number"),
  phoneChoiceOtherNumber: (lang: Lang) => pick(lang, "رقم تاني", "A different number"),
  phoneAskQuestion: (lang: Lang) =>
    pick(lang, "تمام، ابعتلي الرقم (مثال: 01012345678).", "Sure — send me the number (e.g. +20 10 1234 5678)."),
  phoneInvalid: (lang: Lang) =>
    pick(lang, "الرقم ده مش واضح، ممكن تبعته تاني؟", "That number doesn't look right — could you send it again?"),

  nameAskQuestion: (lang: Lang) =>
    pick(lang, "تمام، ممكن اسمك بالكامل؟", "Great — what's your full name?"),
  nameInvalid: (lang: Lang) =>
    pick(lang, "معلش، محتاج اسم أوضح من كده.", "Sorry, I need a fuller name than that."),

  // -- booking ---------------------------------------------------------------------------------
  bookingDoctorQuestion: (lang: Lang) => pick(lang, "تحب تحجز مع أي دكتور؟", "Which doctor would you like to see?"),
  bookingListOpen: (lang: Lang) => pick(lang, "اختار", "Choose"),
  bookingServiceQuestion: (lang: Lang) => pick(lang, "الزيارة دي عشان إيه؟", "What's the visit for?"),
  bookingDateQuestion: (lang: Lang) => pick(lang, "تحب تحجز إمتى؟", "When would you like to come in?"),
  bookingDateOther: (lang: Lang) => pick(lang, "تاريخ تاني", "Another date"),
  bookingDateFreeAsk: (lang: Lang) =>
    pick(lang, "اكتب التاريخ اللي يناسبك (مثال: 12-10-2026).", "Type the date that works for you (e.g. 2026-10-12)."),
  bookingDateInvalid: (lang: Lang) =>
    pick(lang, "معلش، مش قادر أقرأ التاريخ ده. جرب مثلاً 12-10-2026.", "Sorry, I couldn't read that date. Try e.g. 2026-10-12."),
  bookingDatePast: (lang: Lang) => pick(lang, "التاريخ ده فات. اختار تاريخ جاي.", "That date has already passed. Please pick an upcoming one."),
  bookingNoDatesAhead: (lang: Lang) =>
    pick(
      lang,
      "معلش، مفيش مواعيد متاحة للدكتور ده في الأيام الجاية. حابب تجرب دكتور تاني؟",
      "Sorry, there are no open slots with this doctor in the coming days. Would you like to try a different doctor?",
    ),
  bookingSlotQuestion: (lang: Lang) => pick(lang, "اختار الميعاد اللي يناسبك:", "Choose a time that works:"),
  bookingSlotMore: (lang: Lang) => pick(lang, "مواعيد تانية", "More times"),
  bookingNoSlotsOnDate: (lang: Lang) =>
    pick(lang, "معلش، مفيش مواعيد فاضية في اليوم ده. تحب تختار يوم تاني؟", "Sorry, there are no open times that day. Would you like to try another day?"),

  bookingConfirmQuestion: (lang: Lang, doctorName: string, serviceName: string, dateLabel: string, timeLabel: string, patientName: string) =>
    pick(
      lang,
      `تأكيد الحجز:\n👤 ${patientName}\n👨‍⚕️ د. ${doctorName}\n🩺 ${serviceName}\n📅 ${dateLabel}\n🕐 ${timeLabel}\n\nأأكد الحجز؟`,
      `Confirm booking:\n👤 ${patientName}\n👨‍⚕️ Dr. ${doctorName}\n🩺 ${serviceName}\n📅 ${dateLabel}\n🕐 ${timeLabel}\n\nShall I confirm this?`,
    ),
  bookingConfirmButton: (lang: Lang) => pick(lang, "تأكيد", "Confirm"),
  bookingChangeButton: (lang: Lang) => pick(lang, "تغيير", "Change"),
  bookingRestart: (lang: Lang) => pick(lang, "تمام، خلينا نبدأ الحجز من جديد.", "Okay, let's start the booking again."),
  bookingSuccess: (lang: Lang, doctorName: string, dateLabel: string, timeLabel: string) =>
    pick(
      lang,
      `تم الحجز ✅ معاد. د. ${doctorName} — ${dateLabel} الساعة ${timeLabel}.\nلو محتاج حاجة تانية أنا موجود.`,
      `Booked ✅ with Dr. ${doctorName} on ${dateLabel} at ${timeLabel}.\nLet me know if there's anything else.`,
    ),
  bookingSlotTaken: (lang: Lang) =>
    pick(lang, "معلش، حد تاني حجز الميعاد ده لسه. جرب ميعاد تاني.", "Sorry, someone else just took that slot. Please pick another."),

  // -- complaint ---------------------------------------------------------------------------------
  complaintAskQuestion: (lang: Lang) =>
    pick(lang, "معلش على أي حاجة تضايقتلها. احكيلي حصل إيه بالظبط؟", "Sorry to hear that. Please tell me what happened."),
  complaintTooShort: (lang: Lang) =>
    pick(lang, "ممكن توضح أكتر؟", "Could you tell me a bit more?"),
  complaintConfirmQuestion: (lang: Lang, text: string) =>
    pick(lang, `تمام، هبلغ عن:\n"${text}"\n\nأأكد؟`, `Got it, I'll report:\n"${text}"\n\nShall I send this?`),
  complaintConfirmButton: (lang: Lang) => pick(lang, "تأكيد", "Send it"),
  complaintEditButton: (lang: Lang) => pick(lang, "تعديل", "Edit"),
  complaintEditAsk: (lang: Lang) => pick(lang, "تمام، اكتبها تاني.", "Sure, go ahead and rewrite it."),
  complaintSuccess: (lang: Lang, referenceNumber: string) =>
    pick(
      lang,
      `تم تسجيل الشكوى، رقمها ${referenceNumber}. هيتم التواصل معاك في أقرب وقت.\nلو محتاج حاجة تانية أنا موجود.`,
      `Your complaint has been logged, reference ${referenceNumber}. We'll follow up soon.\nLet me know if there's anything else.`,
    ),

  // -- generic ---------------------------------------------------------------------------------
  pleaseUseButtons: (lang: Lang) =>
    pick(lang, "من فضلك اختار من الأزرار اللي فوق 🙏", "Please choose one of the options above 🙏"),
  genericError: (lang: Lang) =>
    pick(lang, "معلش، حصل خطأ. ممكن تجرب تاني؟", "Sorry, something went wrong. Could you try again?"),
} as const;
